import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRef } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const fileInputRef = useRef(null);

  const handleFileUpload = async () => {
    const selectedFile = fileInputRef.current.files[0];
    
    // Create a new FormData object to hold the file data
    const formData = new FormData();
    formData.append('file', selectedFile);
    formData.append('question', 'does the pdf work?');
    formData.append('filename', 'alphaPDF');

    try {
      // Send the file to the backend using a fetch API request to the API route we created
      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData,
      });
      console.log(response);
      if (response.ok) {
        // File uploaded successfully
        console.log('File uploaded successfully.');
      } else {
        // Handle the error if the upload was unsuccessful
        console.error('File upload failed.');
      }
    } catch (error) {
      console.error('An error occurred while uploading the file:', error);
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <input
            type="file"
            ref={fileInputRef}
            style={{ display: 'none' }}
            onChange={handleFileUpload}
          />
          <button onClick={() => fileInputRef.current.click()}>Upload File</button>
        </div>
      </main>
    </>
  )
}
